### ISSUE TITLE
default linters go-require and require-error conflict

### ISSUE THREAD

**Issue by sjiekak** [Antonboom/testifylint#66]
testifylint 1.1.0

```go
var mockHTTPFromFile = func(t *testing.T, w http.ResponseWriter, r *http.Request) {
	t.Helper()
	file, err := os.Open("some file.json")
	require.NoError(t, err)

	data, err := io.ReadAll(file)
	require.NoError(t, err)

	w.Header().Set("Content-Type", "application/json")
	_, err = w.Write(data)
	require.NoError(t, err)
}
```

error : 

```
go-require: require must only be used in the goroutine running the test function (testifylint)
```

if changed to assert

```
require-error: for error assertions use require (testifylint)
```

**Comment by Antonboom** [comment]
hi @sjiekak 
thank you for issue

could you provide an example of usage `mockHTTPFromFile`?
interested in surrounding code

**Comment by sjiekak** [comment]
hi @Antonboom 

The test usually rely on [httptest.Server](https://pkg.go.dev/net/http/httptest#Server)

```go
func Test_Sample(t *testing.T) {
	ts := httptest.NewServer(mockHTTPFromFile(t))
	defer ts.Close()

	client := ts.Client()

	req, err := http.NewRequest("GET", "/antonoboom/example", nil)
	require.NoError(t, err)
	resp, err := client.Do(req)
	require.NoError(t, err)
	defer resp.Body.Close()

	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
```


The alternative is to write the mock server the classic way, and return 5xx codes when things go wrong

**Comment by Antonboom** [comment]
@sjiekak hi again

please, provide the exact compiled example
looks like `mockHTTPFromFile` must be 

```go
var mockHTTPFromFile = func(t *testing.T) http.HandlerFunc {
	t.Helper()

	return func(w http.ResponseWriter, _ *http.Request) {
		file, err := os.Open("some file.json")
		require.NoError(t, err)

		data, err := io.ReadAll(file)
		require.NoError(t, err)

		w.Header().Set("Content-Type", "application/json")
		_, err = w.Write(data)
		require.NoError(t, err)
	}
}
```

right?

But anyway it looks like valid warning, because HTTP server handles request in separate goroutines 🤔 
I'll think about it.

**Comment by Antonboom** [comment]
@sjiekak 

Fixed in https://github.com/Antonboom/testifylint/pull/70
[Tests](https://github.com/Antonboom/testifylint/blob/54a7e02d4dac7d0e85177dee0d3f9b2e806bdbf1/analyzer/testdata/src/go-require-issue66/gorequire_requireerror_conflict_test.go#L14) added.

> But anyway it looks like valid warning, because HTTP server handles requests in separate goroutines 🤔

`go-require` do not look so deeply, after bug fixing it ignores your mock.

`require-error` still wants `require`, but to be honest it should ignore this too, because using assertions there is not the best/clean choice (but more fast and easy yes). Ignoring will introduce necessary complecity to the checker and I left everything as is.

Thanks!

**Comment by sjiekak** [comment]
thanks @Antonboom

**Comment by Antonboom** [comment]
@sjiekak hi!

After https://github.com/Antonboom/testifylint/issues/73#issue-2171958225 I reconsider my decision:

> But anyway it looks like valid warning, because HTTP server handles requests in separate goroutines 🤔
>> My bad. go-require do not look so deeply...

Since [v1.3.0](https://github.com/Antonboom/testifylint/releases/tag/v1.3.0) `testifylint` supports HTTP handlers detection.
To turn off `go-require` warning use `--go-require.ignore-http-handlers`.

Thanks 👌

**Comment by tstirrat15** [comment]
I'm seeing the same issue with `synctest`:

```go
func ExampleTest(t *testing.T) {
  synctest.Test(t, func(t *testing.T) {
    require.NoError(t, fmt.Errorf("oops"))
  })
}
```
This fails with `go-require: require must only be used in the goroutine running the test function`, but:

```go
func ExampleTest(t *testing.T) {
  synctest.Test(t, func(t *testing.T) {
    if !assert.NoError(t, fmt.Errorf("oops")) {
      return
    }
  })
}
```
fails with `require-error: for error assertions use require`.

What's the recommended approach here?
